baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'mushyp3a'
theme = "hugo-bearcub"

[outputs]
home = ["HTML", "RSS", "JSON"]

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]
[params]
  math = true
