baseURL = "https://examplesite.com/"
title = "mushypea"
theme = "hextra"
paginate = 5

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[minify]
  disableXML = true
  minifyOutput = true

[params]
  title = "Hextra Example"
  description = "A Hugo theme for documentation sites"
  defaultTheme = "auto"  # auto, dark, light

  ShowReadingTime = true
  ShowWordCount = true
  ShowPostNavLinks = true
  disableScrollToTop = false
  UseHugoToc = true
  ShowToc = true
  favicon = ""

  [params.theme]
    default = "dark"
    displayToggle = false

  [params.navbar]
    displayLogo = false

  [params.blog]
    [params.blog.list]
      displayTags = true
      sortBy = "date"
      sortOrder = "desc"

  [params.breadcrumbs]
    enable = true

  [params.comments]
    enable = false

  [params.header]
    desktopMode = "fixed"   # "fixed", "normal", "sticky"
    showSearch = true
    logo = ""

  [params.footer]
    enable = true
    displayCopyright = false
    displayPoweredBy = false

  # Search configuration
  [params.search]
    enable = true
    type = "flexsearch"

    [params.search.flexsearch]
      index = "content"  # Index page by: content | summary | heading | title

[params.homeInfoParams]
  Title = "Welcome to Hextra"
  Content = "A beautiful Hugo theme for documentation sites."

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/example"

[[params.socialIcons]]
  name = "twitter"
  url = "https://twitter.com/example"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Blog"
    url = "/blog/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 30

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 20

  [[menu.main]]
    name = "search"
    [[menu.main.params]]
        type = "search"
    weight = 40

  [[menu.main]]
  identifier = "github"
  name = "GitHub"
  url = "https://github.com/mushyp3a"  # Replace with your GitHub profile
  weight = 50
  [menu.main.params]
    icon = "github"  # Uses Hextra's built-in GitHub icon]]

[markup]
  [markup.highlight]
    noClasses = false  # Enables syntax highlighting
